# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pharmacy_pb2 as pharmacy__pb2


class PharmacyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDrug = channel.unary_unary(
                '/pharmacy.PharmacyService/AddDrug',
                request_serializer=pharmacy__pb2.AddDrugRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                )
        self.GetDrug = channel.unary_unary(
                '/pharmacy.PharmacyService/GetDrug',
                request_serializer=pharmacy__pb2.GetDrugRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                )
        self.UpdateStock = channel.unary_unary(
                '/pharmacy.PharmacyService/UpdateStock',
                request_serializer=pharmacy__pb2.UpdateStockRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DrugResponse.FromString,
                )
        self.DeleteDrug = channel.unary_unary(
                '/pharmacy.PharmacyService/DeleteDrug',
                request_serializer=pharmacy__pb2.DeleteDrugRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.DeleteResponse.FromString,
                )
        self.ListDrugs = channel.unary_unary(
                '/pharmacy.PharmacyService/ListDrugs',
                request_serializer=pharmacy__pb2.ListDrugsRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ListDrugsResponse.FromString,
                )
        self.GetLowStock = channel.unary_unary(
                '/pharmacy.PharmacyService/GetLowStock',
                request_serializer=pharmacy__pb2.LowStockRequest.SerializeToString,
                response_deserializer=pharmacy__pb2.ListDrugsResponse.FromString,
                )


class PharmacyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddDrug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDrug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDrug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDrugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLowStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PharmacyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDrug': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDrug,
                    request_deserializer=pharmacy__pb2.AddDrugRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
            'GetDrug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDrug,
                    request_deserializer=pharmacy__pb2.GetDrugRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
            'UpdateStock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStock,
                    request_deserializer=pharmacy__pb2.UpdateStockRequest.FromString,
                    response_serializer=pharmacy__pb2.DrugResponse.SerializeToString,
            ),
            'DeleteDrug': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDrug,
                    request_deserializer=pharmacy__pb2.DeleteDrugRequest.FromString,
                    response_serializer=pharmacy__pb2.DeleteResponse.SerializeToString,
            ),
            'ListDrugs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDrugs,
                    request_deserializer=pharmacy__pb2.ListDrugsRequest.FromString,
                    response_serializer=pharmacy__pb2.ListDrugsResponse.SerializeToString,
            ),
            'GetLowStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLowStock,
                    request_deserializer=pharmacy__pb2.LowStockRequest.FromString,
                    response_serializer=pharmacy__pb2.ListDrugsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pharmacy.PharmacyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PharmacyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddDrug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacy.PharmacyService/AddDrug',
            pharmacy__pb2.AddDrugRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDrug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacy.PharmacyService/GetDrug',
            pharmacy__pb2.GetDrugRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacy.PharmacyService/UpdateStock',
            pharmacy__pb2.UpdateStockRequest.SerializeToString,
            pharmacy__pb2.DrugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDrug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacy.PharmacyService/DeleteDrug',
            pharmacy__pb2.DeleteDrugRequest.SerializeToString,
            pharmacy__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDrugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacy.PharmacyService/ListDrugs',
            pharmacy__pb2.ListDrugsRequest.SerializeToString,
            pharmacy__pb2.ListDrugsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLowStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pharmacy.PharmacyService/GetLowStock',
            pharmacy__pb2.LowStockRequest.SerializeToString,
            pharmacy__pb2.ListDrugsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
