# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pharmacy.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epharmacy.proto\x12\x08pharmacy\"h\n\x04\x44rug\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x65xpiry_date\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\"f\n\x0e\x41\x64\x64\x44rugRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x13\n\x0b\x65xpiry_date\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\"\x1c\n\x0eGetDrugRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x12UpdateStockRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\x1f\n\x11\x44\x65leteDrugRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x12\n\x10ListDrugsRequest\"$\n\x0fLowStockRequest\x12\x11\n\tthreshold\x18\x01 \x01(\x05\"2\n\x11ListDrugsResponse\x12\x1d\n\x05\x64rugs\x18\x01 \x03(\x0b\x32\x0e.pharmacy.Drug\"N\n\x0c\x44rugResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1c\n\x04\x64rug\x18\x03 \x01(\x0b\x32\x0e.pharmacy.Drug2\xa2\x03\n\x0fPharmacyService\x12;\n\x07\x41\x64\x64\x44rug\x12\x18.pharmacy.AddDrugRequest\x1a\x16.pharmacy.DrugResponse\x12;\n\x07GetDrug\x12\x18.pharmacy.GetDrugRequest\x1a\x16.pharmacy.DrugResponse\x12\x43\n\x0bUpdateStock\x12\x1c.pharmacy.UpdateStockRequest\x1a\x16.pharmacy.DrugResponse\x12\x43\n\nDeleteDrug\x12\x1b.pharmacy.DeleteDrugRequest\x1a\x18.pharmacy.DeleteResponse\x12\x44\n\tListDrugs\x12\x1a.pharmacy.ListDrugsRequest\x1a\x1b.pharmacy.ListDrugsResponse\x12\x45\n\x0bGetLowStock\x12\x19.pharmacy.LowStockRequest\x1a\x1b.pharmacy.ListDrugsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pharmacy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DRUG']._serialized_start=28
  _globals['_DRUG']._serialized_end=132
  _globals['_ADDDRUGREQUEST']._serialized_start=134
  _globals['_ADDDRUGREQUEST']._serialized_end=236
  _globals['_GETDRUGREQUEST']._serialized_start=238
  _globals['_GETDRUGREQUEST']._serialized_end=266
  _globals['_UPDATESTOCKREQUEST']._serialized_start=268
  _globals['_UPDATESTOCKREQUEST']._serialized_end=318
  _globals['_DELETEDRUGREQUEST']._serialized_start=320
  _globals['_DELETEDRUGREQUEST']._serialized_end=351
  _globals['_DELETERESPONSE']._serialized_start=353
  _globals['_DELETERESPONSE']._serialized_end=403
  _globals['_LISTDRUGSREQUEST']._serialized_start=405
  _globals['_LISTDRUGSREQUEST']._serialized_end=423
  _globals['_LOWSTOCKREQUEST']._serialized_start=425
  _globals['_LOWSTOCKREQUEST']._serialized_end=461
  _globals['_LISTDRUGSRESPONSE']._serialized_start=463
  _globals['_LISTDRUGSRESPONSE']._serialized_end=513
  _globals['_DRUGRESPONSE']._serialized_start=515
  _globals['_DRUGRESPONSE']._serialized_end=593
  _globals['_PHARMACYSERVICE']._serialized_start=596
  _globals['_PHARMACYSERVICE']._serialized_end=1014
# @@protoc_insertion_point(module_scope)
